In [1]:
import pandas as pd

In [29]:
para_pd = pd.read_csv("/Utilisateurs/umushtaq/am_reasoning/data_files/PE_data_paragraph.csv")

In [30]:
para_pd

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']"
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']"
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[]
...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']"
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']"
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[]

In [31]:
para_pd.para_types.value_counts()

para_types
body          1029
prompt         402
intro          402
conclusion     402
Name: count, dtype: int64

In [32]:
paras_df = para_pd#[para_pd.para_types == "body"].reset_index(drop=True)

In [33]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']"
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']"
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[]
...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']"
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']"
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[]

In [34]:
14227 + 4113 + 3023 + 809

22172

In [35]:
def get_para_ac_count(row):
    
    return len(eval(row.ac_spans))

In [36]:
paras_df['ac_count'] = paras_df.apply(lambda row: get_para_ac_count(row), axis=1)

In [37]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types,ac_count
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[],0
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[],1
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']",4
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']",5
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[],1
...,...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[],0
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[],1
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']",4
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']",4
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[],1

In [59]:
gp_df = paras_df.groupby(['essay_id'], sort=False).agg({
    'para_id': list,
    'para_types': list,
    'ac_count': list,
    'AR_pairs': list,
}).reset_index()

In [60]:
gp_df

,essay_id,para_id,para_types,ac_count,AR_pairs
0,0,"[0, 1, 2, 3, 4]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4..."
1,1,"[5, 6, 7, 8, 9]","[prompt, intro, body, body, conclusion]","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5..."
2,2,"[10, 11, 12, 13, 14]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3..."
3,3,"[15, 16, 17, 18, 19, 20]","[prompt, intro, body, body, body, conclusion]","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3..."
4,4,"[21, 22, 23, 24, 25]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5..."
...,...,...,...,...,...
397,397,"[2208, 2209, 2210, 2211, 2212]","[prompt, intro, body, body, conclusion]","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]"
398,398,"[2213, 2214, 2215, 2216, 2217, 2218]","[prompt, intro, body, body, body, conclusion]","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [..."
399,399,"[2219, 2220, 2221, 2222, 2223]","[prompt, intro, body, body, conclusion]","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1..."
400,400,"[2224, 2225, 2226, 2227, 2228, 2229]","[prompt, intro, body, body, body, conclusion]","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [..."
401,401,"[2230, 2231, 2232, 2233, 2234]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0..."

In [62]:
gp_df.iloc[0]['AR_pairs']

['[]', '[]', '[(0, 1), (0, 2), (0, 3)]', '[(1, 0), (4, 2), (4, 3)]', '[]']

In [45]:
import itertools

In [50]:
para_id = [0, 1, 2, 3, 4]
ac_count = [0, 1, 4, 5, 1]

In [57]:
def generate_pairs(count):
    """Generate all pairs of (i, j) where i != j and neither are 0."""
    return [(i, j) for i, j in itertools.combinations(range(1, count), 2)]  # Starts from 1 to exclude 0

# List to store all paragraph pairs
all_pairs = []

# Variable to keep track of the cumulative count of pairs
cumulative_count = 1  # Start from 1 for the first paragraph

# Iterate through paragraphs
for i in range(len(para_id)):
    # Update the cumulative count by adding the current ac_count
    cumulative_count += ac_count[i]
    
    # Generate pairs based on the cumulative count of previous paragraphs, excluding 0
    pairs = generate_pairs(cumulative_count)
    
    # Add the pairs for this paragraph to the all_pairs list
    all_pairs.append(pairs)

In [58]:
all_pairs

[[],
 [],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (2, 3),
  (2, 4),
  (2, 5),
  (3, 4),
  (3, 5),
  (4, 5)],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (4, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (4, 9),
  (4, 10),
  (5, 6),
  (5, 7),
  (5, 8),
  (5, 9),
  (5, 10),
  (6, 7),
  (6, 8),
  (6, 9),
  (6, 10),
  (7, 8),
  (7, 9),
  (7, 10),
  (8, 9),
  (8, 10),
  (9, 10)],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (1, 11),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (2, 11),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (3, 11),
  (4, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (4, 9),
  (4, 10),
  (4, 11),
  (5, 6),
  (5, 7),
  (5, 8),
  (5, 9),
  (5, 10),
  (5, 11),
  (6, 7),
  (6, 8),
  (6, 9),
  (6, 10),
  (6, 11),
  (7, 8),
  (7, 9),
  (7, 10),
  (7, 11),
  (8, 9),
  (8, 10),
  (8, 11),
  (9, 10),
  (9, 11),
  (10, 11)]]

In [38]:
def get_all_pairs(row):
    
    para_nr_acs = row.ac_count
    all_pairs = [(i, j) for i in range(1, para_nr_acs + 1) for j in range(1, para_nr_acs + 1) if i != j]
    
    return all_pairs

In [39]:
paras_df['all_para_pairs'] = paras_df.apply(lambda row: get_all_pairs(row), axis=1)

In [40]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types,ac_count,all_para_pairs
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[],0,[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[],1,[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']",5,"[(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3..."
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[],1,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[],0,[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[],1,[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[],1,[]

In [41]:
x = paras_df['all_para_pairs'].apply(len).sum()

In [42]:
x

22172