In [249]:
import pandas as pd

In [315]:
para_pd = pd.read_csv("/Utilisateurs/umushtaq/am_reasoning/data_files/PE_data_paragraph.csv")

In [316]:
para_pd

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']"
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']"
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[]
...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']"
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']"
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[]

In [317]:
len(para_pd.essay_id.unique().tolist())

402

In [318]:
para_pd[para_pd.essay_id == 145]

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types
809,145,809,prompt,<prompt> Cheap air travel should be encouraged...,[],[],[],[],[],[]
810,145,810,intro,"<para-intro> In recent years , many airlines o...","[(29, 40), (41, 57)]","[(30, 40), (49, 57)]","[(29, 29), (41, 48)]","['Claim', 'MajorClaim']",[],[]
811,145,811,body,<para-body> It is undeniable that <AC> cheap a...,"[(1, 23), (24, 41), (42, 64), (66, 88)]","[(5, 23), (25, 41), (43, 64), (68, 88)]","[(1, 4), (24, 24), (42, 42), (66, 67)]","['Claim', 'Premise', 'Premise', 'Claim']","[(0, 1), (0, 2)]","['Support', 'Support']"
812,145,812,body,"<para-body> On the other hand , <AC> growing o...","[(1, 17), (19, 46), (48, 60), (61, 79), (81, 1...","[(6, 17), (21, 46), (50, 60), (62, 79), (84, 1...","[(1, 5), (19, 20), (48, 49), (61, 61), (81, 83)]","['Claim', 'Premise', 'Premise', 'Premise', 'Pr...","[(0, 1), (0, 2), (2, 3), (2, 4)]","['Support', 'Support', 'Support', 'Support']"
813,145,813,conclusion,"<para-conclusion> In conclusion , I would argu...","[(1, 18)]","[(8, 18)]","[(1, 7)]",['MajorClaim'],[],[]

In [319]:
para_pd.para_types.value_counts()

para_types
body          1029
prompt         402
intro          402
conclusion     402
Name: count, dtype: int64

In [320]:
paras_df = para_pd#[para_pd.para_types == "body"].reset_index(drop=True)

In [321]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']"
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']"
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[]
...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']"
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']"
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[]

In [322]:
14227 + 4113 + 3023 + 809

22172

In [323]:
def get_para_ac_count(row):
    
    return len(eval(row.ac_spans))

In [324]:
paras_df['ac_count'] = paras_df.apply(lambda row: get_para_ac_count(row), axis=1)

In [325]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types,ac_count
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[],0
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[],1
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']",4
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']",5
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[],1
...,...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[],0
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[],1
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']",4
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']",4
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[],1

In [326]:
gp_df = paras_df.groupby(['essay_id'], sort=False).agg({
    'para_id': list,
    'para_types': list,
    'ac_count': list,
    'AR_pairs': list,
}).reset_index()

In [327]:
gp_df

,essay_id,para_id,para_types,ac_count,AR_pairs
0,0,"[0, 1, 2, 3, 4]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4..."
1,1,"[5, 6, 7, 8, 9]","[prompt, intro, body, body, conclusion]","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5..."
2,2,"[10, 11, 12, 13, 14]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3..."
3,3,"[15, 16, 17, 18, 19, 20]","[prompt, intro, body, body, body, conclusion]","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3..."
4,4,"[21, 22, 23, 24, 25]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5..."
...,...,...,...,...,...
397,397,"[2208, 2209, 2210, 2211, 2212]","[prompt, intro, body, body, conclusion]","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]"
398,398,"[2213, 2214, 2215, 2216, 2217, 2218]","[prompt, intro, body, body, body, conclusion]","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [..."
399,399,"[2219, 2220, 2221, 2222, 2223]","[prompt, intro, body, body, conclusion]","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1..."
400,400,"[2224, 2225, 2226, 2227, 2228, 2229]","[prompt, intro, body, body, body, conclusion]","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [..."
401,401,"[2230, 2231, 2232, 2233, 2234]","[prompt, intro, body, body, conclusion]","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0..."

In [328]:
gp_df.iloc[0]['AR_pairs']

['[]', '[]', '[(0, 1), (0, 2), (0, 3)]', '[(1, 0), (4, 2), (4, 3)]', '[]']

In [329]:
import itertools

In [330]:
para_id = [0, 1, 2, 3, 4]
ac_count = [0, 1, 4, 5, 1]

In [331]:
def generate_pairs(count):
    """Generate all pairs of (i, j) where i != j and neither are 0."""
    return [(i, j) for i, j in itertools.combinations(range(1, count), 2)]  # Starts from 1 to exclude 0

# List to store all paragraph pairs
all_pairs = []

# Variable to keep track of the cumulative count of pairs
cumulative_count = 1  # Start from 1 for the first paragraph

# Iterate through paragraphs
for i in range(len(para_id)):
    # Update the cumulative count by adding the current ac_count
    cumulative_count += ac_count[i]
    
    # Generate pairs based on the cumulative count of previous paragraphs, excluding 0
    pairs = generate_pairs(cumulative_count)
    
    # Add the pairs for this paragraph to the all_pairs list
    all_pairs.append(pairs)

In [332]:
all_pairs

[[],
 [],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (2, 3),
  (2, 4),
  (2, 5),
  (3, 4),
  (3, 5),
  (4, 5)],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (4, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (4, 9),
  (4, 10),
  (5, 6),
  (5, 7),
  (5, 8),
  (5, 9),
  (5, 10),
  (6, 7),
  (6, 8),
  (6, 9),
  (6, 10),
  (7, 8),
  (7, 9),
  (7, 10),
  (8, 9),
  (8, 10),
  (9, 10)],
 [(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (1, 11),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (2, 11),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (3, 11),
  (4, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (4, 9),
  (4, 10),
  (4, 11),
  (5, 6),
  (5, 7),
  (5, 8),
  (5, 9),
  (5, 10),
  (5, 11),
  (6, 7),
  (6, 8),
  (6, 9),
  (6, 10),
  (6, 11),
  (7, 8),
  (7, 9),
  (7, 10),
  (7, 11),
  (8, 9),
  (8, 10),
  (8, 11),
  (9, 10),
  (9, 11),
  (10, 11)]]

In [333]:
def get_all_pairs(row):
    
    para_nr_acs = row.ac_count
    all_pairs = [(i, j) for i in range(1, para_nr_acs + 1) for j in range(1, para_nr_acs + 1) if i != j]
    
    return all_pairs

In [334]:
paras_df['all_para_pairs'] = paras_df.apply(lambda row: get_all_pairs(row), axis=1)

In [335]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types,ac_count,all_para_pairs
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[],0,[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[],1,[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']",5,"[(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3..."
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[],1,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[],0,[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[],1,[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[],1,[]

In [336]:
paras_df.iloc[2]

essay_id                                                          0
para_id                                                           2
para_types                                                     body
para_text         <para-body> First of all , <AC> through cooper...
adu_spans                 [(1, 25), (26, 55), (56, 99), (100, 123)]
ac_spans                  [(5, 25), (27, 55), (57, 99), (101, 123)]
ai_spans                   [(1, 4), (26, 26), (56, 56), (100, 100)]
AC_types                 ['Claim', 'Premise', 'Premise', 'Premise']
AR_pairs                                   [(0, 1), (0, 2), (0, 3)]
AR_types                          ['Support', 'Support', 'Support']
ac_count                                                          4
all_para_pairs    [(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4...
Name: 2, dtype: object

In [337]:
paras_df.iloc[2]['all_para_pairs']

[(1, 2),
 (1, 3),
 (1, 4),
 (2, 1),
 (2, 3),
 (2, 4),
 (3, 1),
 (3, 2),
 (3, 4),
 (4, 1),
 (4, 2),
 (4, 3)]

In [338]:
x = paras_df['all_para_pairs'].apply(len).sum()

In [339]:
x

22172

In [340]:
paras_df

,essay_id,para_id,para_types,para_text,adu_spans,ac_spans,ai_spans,AC_types,AR_pairs,AR_types,ac_count,all_para_pairs
0,0,0,prompt,<prompt> Should students be taught to compete ...,[],[],[],[],[],[],0,[]
1,0,1,intro,<para-intro> It is always said that competitio...,"[(76, 97)]","[(86, 97)]","[(76, 85)]",['MajorClaim'],[],[],1,[]
2,0,2,body,"<para-body> First of all , <AC> through cooper...","[(1, 25), (26, 55), (56, 99), (100, 123)]","[(5, 25), (27, 55), (57, 99), (101, 123)]","[(1, 4), (26, 26), (56, 56), (100, 100)]","['Claim', 'Premise', 'Premise', 'Premise']","[(0, 1), (0, 2), (0, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
3,0,3,body,"<para-body> On the other hand , <AC> the signi...","[(1, 22), (24, 37), (39, 63), (76, 139), (155,...","[(6, 22), (30, 37), (41, 63), (77, 139), (156,...","[(1, 5), (24, 29), (39, 40), (76, 76), (155, 1...","['Premise', 'Claim', 'Premise', 'Premise', 'Cl...","[(1, 0), (4, 2), (4, 3)]","['Support', 'Support', 'Support']",5,"[(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3..."
4,0,4,conclusion,"<para-conclusion> Consequently , no matter fro...","[(1, 40)]","[(25, 40)]","[(1, 24)]",['MajorClaim'],[],[],1,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2230,401,2230,prompt,<prompt> A greater proportion of the budget sh...,[],[],[],[],[],[],0,[]
2231,401,2231,intro,"<para-intro> In today ' s world , the concept ...","[(26, 51)]","[(33, 51)]","[(26, 32)]",['MajorClaim'],[],[],1,[]
2232,401,2232,body,<para-body> <AC> The first reason why educatio...,"[(0, 22), (24, 56), (58, 71), (72, 98)]","[(1, 22), (27, 56), (60, 71), (74, 98)]","[(0, 0), (24, 26), (58, 59), (72, 73)]","['Premise', 'Premise', 'Claim', 'Premise']","[(2, 0), (2, 1), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2233,401,2233,body,<para-body> The second reason why <AC> governm...,"[(1, 25), (27, 53), (55, 88), (90, 128)]","[(5, 25), (31, 53), (57, 88), (93, 128)]","[(1, 4), (27, 30), (55, 56), (90, 92)]","['Claim', 'Premise', 'Premise', 'Premise']","[(2, 1), (0, 2), (2, 3)]","['Support', 'Support', 'Support']",4,"[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4..."
2234,401,2234,conclusion,"<para-conclusion> In conclusion , <AC> a great...","[(1, 37)]","[(4, 37)]","[(1, 3)]",['MajorClaim'],[],[],1,[]

In [342]:
essays_df = paras_df.groupby(["essay_id"]).agg({
    
    "para_id": list,
    "para_text": list,
    "AR_types": list,
    "ac_count": list,
    "AR_pairs": list,
    "AC_types": list,
    "all_para_pairs": list,
    
}).reset_index(drop=True)

In [343]:
essays_df

,para_id,para_text,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs
0,"[0, 1, 2, 3, 4]",[<prompt> Should students be taught to compete...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
1,"[5, 6, 7, 8, 9]",[<prompt> More people are migrating to other c...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ..."
2,"[10, 11, 12, 13, 14]",[<prompt> International tourism is now more co...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
3,"[15, 16, 17, 18, 19, 20]",[<prompt> Will newspapers become a thing of th...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
4,"[21, 22, 23, 24, 25]","[<prompt> Government budget focus , young chil...","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]",[<prompt> The maintenance of traditional skill...,"[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ..."
398,"[2213, 2214, 2215, 2216, 2217, 2218]",[<prompt> University education restriction </p...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
399,"[2219, 2220, 2221, 2222, 2223]",[<prompt> Police force carries guns - signific...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ..."
400,"[2224, 2225, 2226, 2227, 2228, 2229]",[<prompt> Gun control and increasing violence ...,"[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ..."
401,"[2230, 2231, 2232, 2233, 2234]",[<prompt> A greater proportion of the budget s...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."

In [344]:
essays_df.iloc[0]['para_text']

['<prompt> Should students be taught to compete or to cooperate ? </prompt>',
 "<para-intro> It is always said that competition can effectively promote the development of economy . In order to survive in the competition , companies continue to improve their products and service , and as a result , the whole society prospers . However , when we discuss the issue of competition or cooperation , what we are concerned about is not the whole society , but the development of an individual ' s whole life . From this point of view , I firmly believe that <AC> we should attach more importance to cooperation during primary education </AC> . </para-intro>",
 '<para-body> First of all , <AC> through cooperation , children can learn about interpersonal skills which are significant in the future life of all students </AC> . <AC> What we acquired from team work is not only how to achieve the same goal with others but more importantly , how to get along with others </AC> . <AC> During the process of cooperation , children can learn about how to listen to opinions of others , how to communicate with others , how to think comprehensively , and even how to compromise with other team members when conflicts occurred </AC> . <AC> All of these skills help them to get on well with other people and will benefit them for the whole life </AC> . </para-body>',
 '<para-body> On the other hand , <AC> the significance of competition is that how to become more excellence to gain the victory </AC> . Hence it is always said that <AC> competition makes the society more effective </AC> . However , <AC> when we consider about the question that how to win the game , we always find that we need the cooperation </AC> . The greater our goal is , the more competition we need . <AC> Take Olympic games which is a form of competition for instance , it is hard to imagine how an athlete could win the game without the training of his or her coach , and the help of other professional staffs such as the people who take care of his diet , and those who are in charge of the medical care </AC> . The winner is the athlete but the success belongs to the whole team . Therefore <AC> without the cooperation , there would be no victory of competition </AC> . </para-body>',
 "<para-conclusion> Consequently , no matter from the view of individual development or the relationship between competition and cooperation we can receive the same conclusion that <AC> a more cooperative attitudes towards life is more profitable in one ' s success </AC> . </para-conclusion>"]

In [351]:
def get_title(row):
    
    return row.para_text[0].replace("<prompt> ", "").replace(" </prompt>", "")

In [352]:
get_title(essays_df.iloc[0])

'Should students be taught to compete or to cooperate ?'

In [353]:
essays_df["prompts"] = essays_df.apply(lambda row: get_title(row), axis=1)

In [354]:
essays_df.iloc[78]['ac_count']

[0, 0, 5, 5, 3, 1]

In [355]:
essays_df["p_id"] = essays_df.apply(lambda row: list(range(len(row.para_id))), axis=1)

In [356]:
essays_df

,para_id,para_text,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs,prompts,p_id
0,"[0, 1, 2, 3, 4]",[<prompt> Should students be taught to compete...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Should students be taught to compete or to coo...,"[0, 1, 2, 3, 4]"
1,"[5, 6, 7, 8, 9]",[<prompt> More people are migrating to other c...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",More people are migrating to other countries t...,"[0, 1, 2, 3, 4]"
2,"[10, 11, 12, 13, 14]",[<prompt> International tourism is now more co...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",International tourism is now more common than ...,"[0, 1, 2, 3, 4]"
3,"[15, 16, 17, 18, 19, 20]",[<prompt> Will newspapers become a thing of th...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Will newspapers become a thing of the past ?,"[0, 1, 2, 3, 4, 5]"
4,"[21, 22, 23, 24, 25]","[<prompt> Government budget focus , young chil...","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","Government budget focus , young children or un...","[0, 1, 2, 3, 4]"
...,...,...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]",[<prompt> The maintenance of traditional skill...,"[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",The maintenance of traditional skills and ways...,"[0, 1, 2, 3, 4]"
398,"[2213, 2214, 2215, 2216, 2217, 2218]",[<prompt> University education restriction </p...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",University education restriction,"[0, 1, 2, 3, 4, 5]"
399,"[2219, 2220, 2221, 2222, 2223]",[<prompt> Police force carries guns - signific...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",Police force carries guns - significant impact...,"[0, 1, 2, 3, 4]"
400,"[2224, 2225, 2226, 2227, 2228, 2229]",[<prompt> Gun control and increasing violence ...,"[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",Gun control and increasing violence,"[0, 1, 2, 3, 4, 5]"
401,"[2230, 2231, 2232, 2233, 2234]",[<prompt> A greater proportion of the budget s...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",A greater proportion of the budget should be a...,"[0, 1, 2, 3, 4]"

In [357]:
def offset_pair_indices(row):
    
    ac_count = row.ac_count
    p_ids = row.p_id
    para_pairs = row.all_para_pairs
    
    new_para_pairs = []
    
    for p in p_ids:
        
        offset = sum([elem for elem in ac_count[:p]])
        #para_pairs_p = para_pairs[p]
        new_para = [(i + offset, j + offset) for i, j in para_pairs[p]]
        new_para_pairs.append(new_para)
        
    return new_para_pairs

In [358]:
essays_df["correct_para_pairs"] = essays_df.apply(lambda row: offset_pair_indices(row), axis=1)

In [359]:
essays_df

,para_id,para_text,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs,prompts,p_id,correct_para_pairs
0,"[0, 1, 2, 3, 4]",[<prompt> Should students be taught to compete...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Should students be taught to compete or to coo...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ..."
1,"[5, 6, 7, 8, 9]",[<prompt> More people are migrating to other c...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",More people are migrating to other countries t...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ..."
2,"[10, 11, 12, 13, 14]",[<prompt> International tourism is now more co...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",International tourism is now more common than ...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ..."
3,"[15, 16, 17, 18, 19, 20]",[<prompt> Will newspapers become a thing of th...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Will newspapers become a thing of the past ?,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ..."
4,"[21, 22, 23, 24, 25]","[<prompt> Government budget focus , young chil...","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","Government budget focus , young children or un...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ..."
...,...,...,...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]",[<prompt> The maintenance of traditional skill...,"[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",The maintenance of traditional skills and ways...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ..."
398,"[2213, 2214, 2215, 2216, 2217, 2218]",[<prompt> University education restriction </p...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",University education restriction,"[0, 1, 2, 3, 4, 5]","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ..."
399,"[2219, 2220, 2221, 2222, 2223]",[<prompt> Police force carries guns - signific...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",Police force carries guns - significant impact...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ..."
400,"[2224, 2225, 2226, 2227, 2228, 2229]",[<prompt> Gun control and increasing violence ...,"[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",Gun control and increasing violence,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ..."
401,"[2230, 2231, 2232, 2233, 2234]",[<prompt> A greater proportion of the budget s...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",A greater proportion of the budget should be a...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ..."

In [360]:
def offset_ar_indices(row):
    
    ac_count = row.ac_count
    p_ids = row.p_id
    para_pairs = row.AR_pairs
    #print(para_pairs)
    
    new_para_pairs = []
    
    for p in p_ids:
        
        offset = sum([elem for elem in ac_count[:p]])
        #para_pairs_p = para_pairs[p]
        #print(para_pairs[p])
        new_para = [(i + offset +1, j + offset +1) for i, j in eval(para_pairs[p])]
        new_para_pairs.append(new_para)
        
    return new_para_pairs

In [361]:
essays_df["corrected_true_pairs"] = essays_df.apply(lambda row: offset_ar_indices(row), axis=1)

In [362]:
essays_df

,para_id,para_text,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs,prompts,p_id,correct_para_pairs,corrected_true_pairs
0,"[0, 1, 2, 3, 4]",[<prompt> Should students be taught to compete...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Should students be taught to compete or to coo...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(2, 3), (2, 4), (2, 5)], [(7, 6), (1..."
1,"[5, 6, 7, 8, 9]",[<prompt> More people are migrating to other c...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",More people are migrating to other countries t...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (6, 3), (6, 4), (6, 5)], [(1..."
2,"[10, 11, 12, 13, 14]",[<prompt> International tourism is now more co...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",International tourism is now more common than ...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9..."
3,"[15, 16, 17, 18, 19, 20]",[<prompt> Will newspapers become a thing of th...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Will newspapers become a thing of the past ?,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9..."
4,"[21, 22, 23, 24, 25]","[<prompt> Government budget focus , young chil...","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","Government budget focus , young children or un...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(11, 6), (..."
...,...,...,...,...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]",[<prompt> The maintenance of traditional skill...,"[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",The maintenance of traditional skills and ways...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], []]"
398,"[2213, 2214, 2215, 2216, 2217, 2218]",[<prompt> University education restriction </p...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",University education restriction,"[0, 1, 2, 3, 4, 5]","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[[], [], [(1, 2), (1, 3), (1, 4)], [(6, 5)], [..."
399,"[2219, 2220, 2221, 2222, 2223]",[<prompt> Police force carries guns - signific...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",Police force carries guns - significant impact...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (4, 3), (6, 4), (6, 5)], [(8..."
400,"[2224, 2225, 2226, 2227, 2228, 2229]",[<prompt> Gun control and increasing violence ...,"[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",Gun control and increasing violence,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], [..."
401,"[2230, 2231, 2232, 2233, 2234]",[<prompt> A greater proportion of the budget s...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",A greater proportion of the budget should be a...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(4, 2), (4, 3), (4, 5)], [(8, 7), (6..."

In [363]:
def get_correct_triplets(row):
    
    true_pairs = row.corrected_true_pairs
    all_pairs = row.correct_para_pairs
    pair_types = [eval(elem) for elem in row.AR_types]
    
    
    all_triplets = []
    correct_triplets = []
   
    
    
    # for i, para_pairs in enumerate(all_pairs):
        
    #     for j, para_pair in enumerate(para_pairs):
        
    #         all_triplets.append((para_pair, "NR"))
    
    for p in para_id:
        
        tmp = []
        
        for pair in all_pairs[p]:
            
            tmp.append((pair, "NR"))
            
        all_triplets.append(tmp)
        
        
    for p in para_id:
        
        tmp = []
        
        for i, pair in enumerate(true_pairs[p]):
            
            tmp.append((pair, pair_types[p][i]))
            
        correct_triplets.append(tmp)
        
    for p in para_id:
        
        #tmp = all_triplets[p]
        
        for pair, rel_type in correct_triplets[p]:
            
            for i, data in enumerate(all_triplets[p]):
                
                if data[0] == pair:
                
                    all_triplets[p][i] = (data[0], rel_type)
        
        
        
    
    
    
    # for i, para_pairs in enumerate(all_pairs):
        
    #     for j, para_pair in enumerate(para_pairs):
            
    #         if para_pair not in true_pairs[i][j]:
                
    #             triplets.append((para_pair, "NR"))
    #         else:
    #             triplets.append((para_pair, pair_types[i][j]))
    
    # for i, (para_pairs, true_para_pairs) in enumerate(zip(all_pairs, true_pairs)):
        
    #     for j, para_pair in enumerate(para_pairs):
            
    #         if para_pair not in true_para_pairs:
                
    #             triplets.append((para_pair, "NR"))
    #         else:
                
    #             triplets.append((para_pair, pair_types[i][j]))
        
    return all_triplets#, correct_triplets

In [364]:
get_correct_triplets(essays_df.iloc[0])

[[],
 [],
 [((2, 3), 'Support'),
  ((2, 4), 'Support'),
  ((2, 5), 'Support'),
  ((3, 2), 'NR'),
  ((3, 4), 'NR'),
  ((3, 5), 'NR'),
  ((4, 2), 'NR'),
  ((4, 3), 'NR'),
  ((4, 5), 'NR'),
  ((5, 2), 'NR'),
  ((5, 3), 'NR'),
  ((5, 4), 'NR')],
 [((6, 7), 'NR'),
  ((6, 8), 'NR'),
  ((6, 9), 'NR'),
  ((6, 10), 'NR'),
  ((7, 6), 'Support'),
  ((7, 8), 'NR'),
  ((7, 9), 'NR'),
  ((7, 10), 'NR'),
  ((8, 6), 'NR'),
  ((8, 7), 'NR'),
  ((8, 9), 'NR'),
  ((8, 10), 'NR'),
  ((9, 6), 'NR'),
  ((9, 7), 'NR'),
  ((9, 8), 'NR'),
  ((9, 10), 'NR'),
  ((10, 6), 'NR'),
  ((10, 7), 'NR'),
  ((10, 8), 'Support'),
  ((10, 9), 'Support')],
 []]

In [365]:
essays_df["triplets"] = essays_df.apply(lambda row: get_correct_triplets(row), axis=1)

In [366]:
essays_df.iloc[0]['corrected_true_pairs']

[[], [], [(2, 3), (2, 4), (2, 5)], [(7, 6), (10, 8), (10, 9)], []]

In [367]:
essays_df.iloc[0]

para_id                                                   [0, 1, 2, 3, 4]
para_text               [<prompt> Should students be taught to compete...
AR_types                [[], [], ['Support', 'Support', 'Support'], ['...
ac_count                                                  [0, 1, 4, 5, 1]
AR_pairs                [[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...
AC_types                [[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...
all_para_pairs          [[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...
prompts                 Should students be taught to compete or to coo...
p_id                                                      [0, 1, 2, 3, 4]
correct_para_pairs      [[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...
corrected_true_pairs    [[], [], [(2, 3), (2, 4), (2, 5)], [(7, 6), (1...
triplets                [[], [], [((2, 3), Support), ((2, 4), Support)...
Name: 0, dtype: object

In [368]:
essays_df

,para_id,para_text,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs,prompts,p_id,correct_para_pairs,corrected_true_pairs,triplets
0,"[0, 1, 2, 3, 4]",[<prompt> Should students be taught to compete...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Should students be taught to compete or to coo...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(2, 3), (2, 4), (2, 5)], [(7, 6), (1...","[[], [], [((2, 3), Support), ((2, 4), Support)..."
1,"[5, 6, 7, 8, 9]",[<prompt> More people are migrating to other c...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",More people are migrating to other countries t...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (6, 3), (6, 4), (6, 5)], [(1...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."
2,"[10, 11, 12, 13, 14]",[<prompt> International tourism is now more co...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",International tourism is now more common than ...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."
3,"[15, 16, 17, 18, 19, 20]",[<prompt> Will newspapers become a thing of th...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",Will newspapers become a thing of the past ?,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."
4,"[21, 22, 23, 24, 25]","[<prompt> Government budget focus , young chil...","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","Government budget focus , young children or un...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(11, 6), (...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."
...,...,...,...,...,...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]",[<prompt> The maintenance of traditional skill...,"[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",The maintenance of traditional skills and ways...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], []]","[[], [], [((2, 3), Support), ((2, 4), Support)..."
398,"[2213, 2214, 2215, 2216, 2217, 2218]",[<prompt> University education restriction </p...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",University education restriction,"[0, 1, 2, 3, 4, 5]","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[[], [], [(1, 2), (1, 3), (1, 4)], [(6, 5)], [...","[[], [], [((1, 2), Support), ((1, 3), Support)..."
399,"[2219, 2220, 2221, 2222, 2223]",[<prompt> Police force carries guns - signific...,"[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...",Police force carries guns - significant impact...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (4, 3), (6, 4), (6, 5)], [(8...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."
400,"[2224, 2225, 2226, 2227, 2228, 2229]",[<prompt> Gun control and increasing violence ...,"[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...",Gun control and increasing violence,"[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], [...","[[], [], [((2, 3), Support), ((2, 4), Attack),..."
401,"[2230, 2231, 2232, 2233, 2234]",[<prompt> A greater proportion of the budget s...,"[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...",A greater proportion of the budget should be a...,"[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(4, 2), (4, 3), (4, 5)], [(8, 7), (6...","[[], [], [((2, 3), NR), ((2, 4), NR), ((2, 5),..."

In [369]:
df = pd.read_csv("/Utilisateurs/umushtaq/am_reasoning/data_files/pe_dataset_final.csv", index_col=0)

In [370]:
df

,ann_file_name,argument_ids,argument_types,arg_start_bounds,arg_end_bounds,argument_components,source_args,target_args,relation_types,stance_types,essay_title,essay_text,source_acs,target_acs,relation_pairs,stance_pairs,split
0,essay001.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['503', '2154', '591', '716', '853', '1088', '...","['575', '2231', '714', '851', '1086', '1191', ...",['we should attach more importance to cooperat...,"['T4', 'T5', 'T6', 'T10', 'T9', 'T8']","['T3', 'T3', 'T3', 'T11', 'T11', 'T7']","['supports', 'supports', 'supports', 'supports...","['For', 'Against', 'For']",Should students be taught to compete or to coo...,It is always said that competition can effecti...,['What we acquired from team work is not only ...,"['through cooperation, children can learn abou...","[(4, 3, 'supports'), (5, 3, 'supports'), (6, 3...","[(3, 1, 'For'), (3, 2, 'For'), (7, 1, 'Against...",TRAIN
1,essay002.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Premise', 'Claim...","['391', '1936', '500', '1089', '626', '841', '...","['489', '2077', '624', '1156', '839', '946', '...",['they are able to sustain their cultural iden...,"['T9', 'T11', 'T12', 'T13', 'T5', 'T6', 'T7', ...","['T8', 'T10', 'T10', 'T10', 'T4', 'T4', 'T4', ...","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'Against']",More people are migrating to other countries t...,The last 50 years have seen an increasing numb...,['they need a connection back to their country...,"['it is crucial to keep oneâ€™s identity', 'keep...","[(9, 8, 'supports'), (11, 10, 'supports'), (12...","[(4, 1, 'For'), (4, 2, 'For'), (10, 1, 'For'),...",TRAIN
2,essay003.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['352', '1568', '955', '487', '615', '786', '1...","['475', '1701', '1012', '613', '784', '943', '...",['it has contributed to the economic developme...,"['T10', 'T9', 'T6', 'T5', 'T4', 'T7']","['T8', 'T8', 'T3', 'T3', 'T3', 'T8']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",International tourism is now more common than ...,The last decade has seen an increasing number ...,['Without this support and profit from tourism...,['tourism has survived many non-tangible cultu...,"[(10, 8, 'supports'), (9, 8, 'supports'), (6, ...","[(3, 1, 'For'), (3, 2, 'For'), (8, 1, 'For'), ...",TRAIN
3,essay004.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Claim',...","['262', '1663', '179', '953', '1578', '417', '...","['376', '1758', '239', '1031', '1624', '530', ...",['this industry has affected the cultural attr...,"['T8', 'T7', 'T6', 'T10', 'T9', 'T11']","['T4', 'T4', 'T4', 'T11', 'T5', 'T5']","['supports', 'supports', 'supports', 'supports...","['Against', 'For', 'For']",International tourism is now more common than ...,The last 50 years have seen a significant incr...,['This was due to the lack of adequate control...,['international tourism can create negative im...,"[(8, 4, 'supports'), (7, 4, 'supports'), (6, 4...","[(3, 1, 'Against'), (3, 2, 'Against'), (4, 1, ...",TEST
4,essay005.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Claim',...","['286', '1535', '388', '775', '1330', '566', '...","['359', '1652', '564', '883', '1425', '765', '...",['one who studies overseas will gain many skil...,"['T6', 'T7', 'T8', 'T9', 'T10', 'T11']","['T3', 'T4', 'T7', 'T4', 'T5', 'T5']","['supports', 'attacks', 'attacks', 'supports',...","['For', 'For', 'For', 'Against']",Living and studying overseas,It is every student's desire to study at a goo...,['Compared to the peers studying in the home c...,['studying at an overseas university gives ind...,"[(6, 3, 'supports'), (7, 4, 'attacks'), (8, 7,...","[(3, 1, 'For'), (3, 2, 'For'), (4, 1, 'For'), ...",TEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,essay398.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['Claim', 'MajorClaim', 'Premise', 'Premise', ...","['254', '1751', '409', '557', '647', '778', '9...","['318', '1951', '541', '645', '767', '897', '1...",['many different characters exist between male...,"['T3', 'T4', 'T5', 'T6', 'T7', 'T13', 'T14', '...","['T8', 'T8', 'T8', 'T8', 'T8', 'T12', 'T12', '...","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'For', 'For']",We can not forcedly put the same numbers of ma...,There is a view that universities and colleges...,['Most of male students tend to use their left...,['boys and girls have the diversity in psychol...,"[(3, 8, 'supports'), (4, 8, 'supports'), (5, 8...","[(1, 2, 'For'), (8, 2, 'For'), (10, 2, 'For'),...",TEST
398,essay399.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['367', '1323', '527', '431', '661', '787', '9...","['429', '1390', '645', '525', '737', '951', '1...",['this is a worrying tread which has negative ...,"['T4', 'T5', 'T6', 'T8', 'T10']","['T3', 'T3', 'T7', 'T7', 'T9']","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'For']","Drugs, alcohol and messy sex lives","Celebrities, for example movie stars, are usua...",['The first impression of the celebrities seem...,['This gives children the idea that it is not ...,"[(4, 3, 'supports'), (5, 3, 'supports'), (6, 7...","[(3, 1, 'For'), (3, 2, 'For'), (7, 1, 'For'), ...",TRAIN
399,essay400.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['274', '1619', '736', '541', '805', '389', '1...","['387', '1812', '796', '723', '944', '524', '1...",['governments should devote a greater portion ...,"['T4', 'T5', 'T6', 'T7', 'T9', 'T8']","['T3', 'T3', 'T3', 'T8', 'T8', 'T10']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",A greater proportion of the budget should be a...,"In today's world, the concept of the welfare s...",['decreasing the number of patients in the hea...,['society should be educated and became aware ...,"[(4, 3, 'supports'), (5, 3, 'supports'), (6, 3...","[(3, 1, 'For'), (3, 2, 'For'), (10, 1, 'For'),...",TRAIN
400,essay401.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Premise', 'Premi...","['311', '1496', '502', '622', '386', '954', '1...","['384', '1667', '607', '815', '488', '1087', '...",['fatherhood is a as vital part of a healty pa...,"['T3', 'T7', 'T10', 'T4', 'T9', 'T6']","['T5', 'T6', 'T8', 'T3', 'T8', 'T8']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",Fatherhood should be as present as motherhood ...,"In today's world, having and raising children ...","[""the role models within a family play a signi...","[""The first reason why the father's role shoul...","[(3, 5, 'supports'), (7, 6, 'supports'), (10, ...","[(5, 1, 'For'), (5, 2, 'For'), (8, 1, 'For'), ...",TRAIN
401,essay402.ann,"['T1', 'T2', 'T3', 'T5', 'T6', 'T7', 'T8', 'T4...","['MajorClaim', 'MajorClaim', 'Premise', 'Premi...","['238', '1543', '379', '544', '725', '827', '3...","['307', '1620', '462', '723', '810', '896', '3...",['both of studying hard and playing sports are...,"['T5', 'T3', 'T6', 'T11', 'T12', 'T4', 'T13', ...","['T8', 'T8', 'T5', 'T10', 'T13', 'T15', 'T4', ...","['supports', 'supports', 'supports', 'supports...","['For', 'For']",Children should studying hard or playing sport...,Some people believe that studying hard is esse...,['children who always studying hard and gettin...,['studying hard will give children a better fu...,"[(4, 7, 'supports'), (3, 7, 'supports'), (5, 4...","[(7, 1, 'For'), (7, 2, 'For'), (15, 1, 'For'),...",TRAIN

In [374]:
df.iloc[0]

ann_file_name                                               essay001.ann
argument_ids           ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...
argument_types         ['MajorClaim', 'MajorClaim', 'Claim', 'Premise...
arg_start_bounds       ['503', '2154', '591', '716', '853', '1088', '...
arg_end_bounds         ['575', '2231', '714', '851', '1086', '1191', ...
argument_components    ['we should attach more importance to cooperat...
source_args                        ['T4', 'T5', 'T6', 'T10', 'T9', 'T8']
target_args                       ['T3', 'T3', 'T3', 'T11', 'T11', 'T7']
relation_types         ['supports', 'supports', 'supports', 'supports...
stance_types                                   ['For', 'Against', 'For']
essay_title            Should students be taught to compete or to coo...
essay_text             It is always said that competition can effecti...
source_acs             ['What we acquired from team work is not only ...
target_acs             ['through cooperation, children can learn abou...
relation_pairs         [(4, 3, 'supports'), (5, 3, 'supports'), (6, 3...
stance_pairs           [(3, 1, 'For'), (3, 2, 'For'), (7, 1, 'Against...
split                                                              TRAIN
Name: 0, dtype: object

In [372]:
df.columns

Index(['ann_file_name', 'argument_ids', 'argument_types', 'arg_start_bounds',
       'arg_end_bounds', 'argument_components', 'source_args', 'target_args',
       'relation_types', 'stance_types', 'essay_title', 'essay_text',
       'source_acs', 'target_acs', 'relation_pairs', 'stance_pairs', 'split'],
      dtype='object')

In [373]:
para_pd.columns

Index(['essay_id', 'para_id', 'para_types', 'para_text', 'adu_spans',
       'ac_spans', 'ai_spans', 'AC_types', 'AR_pairs', 'AR_types', 'ac_count',
       'all_para_pairs'],
      dtype='object')

In [346]:
df.iloc[0]['essay_title']

'Should students be taught to compete or to cooperate?'

In [300]:
len([elem for elem in eval(df.iloc[78]['argument_components'])])

16

In [302]:
[elem for elem in eval(df.iloc[78]['argument_components'])]

["arts are supposed to be included in the government's investment as well",
 'the government should give priority to public services and facilities',
 'public services and facilities should be given adequate attention by the authorities to maintain social stability',
 'the government plays the role of a leader among citizens, which should discharge the responsibility of making optimal use of the tax money to keep society safe and stable',
 "public services such as education system or medical care can meet people's basic demand of survival, security and knowledge, thus making them feel comfortable, which can lower the crime rate",
 'arts should by no means been disregarded by the government',
 "arts can enrich people's cultural lives",
 'Currently, people are increasingly occupied with their work and studies due to the stiff competition',
 'they require various entertainment such as music, movies or books to them ease their minds and release pressure',
 'Without arts, people would be at risk of suffering psychological problems',
 'public services and facilities are an integral part of the government expenditure',
 'the authorities should also respect the value of arts which are individually and socially advantageous',
 'funding arts is beneficial to the local cultural and economic development',
 'Cultural heritage constitutes an essential part of arts',
 'preserving local arts may promote the preservation of the local cultural heritage, which not only helps the local people have a sense of belonging but also contributes to the booming local tourism industry',
 'arts serve cultural and economic purposes']

In [301]:
essays_df.iloc[78]['AC_types']

['[]',
 '[]',
 "['Premise', 'Premise', 'Premise', 'Premise', 'Claim']",
 "['Claim', 'Premise', 'Premise', 'Premise', 'Claim']",
 "['Claim', 'Premise', 'Premise']",
 "['MajorClaim']"]

In [199]:
def get_sorted_acs(row):
    
    #arg_bounds = eval([int(eval(elem)) for elem in row.arg_start_bounds])
    #print(type(eval(row.arg_start_bounds)))
    arg_comps = [elem for elem in eval(row.argument_components)]
    arg_bounds = [int(elem) for elem in eval(row.arg_start_bounds)]
    #print(arg_bounds)
    sorted_indices = sorted(range(len(arg_bounds)), key=lambda k: arg_bounds[k])
    
    return [arg_comps[i] for i in sorted_indices]

In [200]:
df["sorted_acs"] = df.apply(lambda row: get_sorted_acs(row), axis=1)

In [201]:
df

,ann_file_name,argument_ids,argument_types,arg_start_bounds,arg_end_bounds,argument_components,source_args,target_args,relation_types,stance_types,essay_title,essay_text,source_acs,target_acs,relation_pairs,stance_pairs,split,sorted_acs
0,essay001.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['503', '2154', '591', '716', '853', '1088', '...","['575', '2231', '714', '851', '1086', '1191', ...",['we should attach more importance to cooperat...,"['T4', 'T5', 'T6', 'T10', 'T9', 'T8']","['T3', 'T3', 'T3', 'T11', 'T11', 'T7']","['supports', 'supports', 'supports', 'supports...","['For', 'Against', 'For']",Should students be taught to compete or to coo...,It is always said that competition can effecti...,['What we acquired from team work is not only ...,"['through cooperation, children can learn abou...","[(4, 3, 'supports'), (5, 3, 'supports'), (6, 3...","[(3, 1, 'For'), (3, 2, 'For'), (7, 1, 'Against...",TRAIN,[we should attach more importance to cooperati...
1,essay002.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Premise', 'Claim...","['391', '1936', '500', '1089', '626', '841', '...","['489', '2077', '624', '1156', '839', '946', '...",['they are able to sustain their cultural iden...,"['T9', 'T11', 'T12', 'T13', 'T5', 'T6', 'T7', ...","['T8', 'T10', 'T10', 'T10', 'T4', 'T4', 'T4', ...","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'Against']",More people are migrating to other countries t...,The last 50 years have seen an increasing numb...,['they need a connection back to their country...,"['it is crucial to keep oneâ€™s identity', 'keep...","[(9, 8, 'supports'), (11, 10, 'supports'), (12...","[(4, 1, 'For'), (4, 2, 'For'), (10, 1, 'For'),...",TRAIN,[they are able to sustain their cultural ident...
2,essay003.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['352', '1568', '955', '487', '615', '786', '1...","['475', '1701', '1012', '613', '784', '943', '...",['it has contributed to the economic developme...,"['T10', 'T9', 'T6', 'T5', 'T4', 'T7']","['T8', 'T8', 'T3', 'T3', 'T3', 'T8']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",International tourism is now more common than ...,The last decade has seen an increasing number ...,['Without this support and profit from tourism...,['tourism has survived many non-tangible cultu...,"[(10, 8, 'supports'), (9, 8, 'supports'), (6, ...","[(3, 1, 'For'), (3, 2, 'For'), (8, 1, 'For'), ...",TRAIN,[it has contributed to the economic developmen...
3,essay004.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Claim',...","['262', '1663', '179', '953', '1578', '417', '...","['376', '1758', '239', '1031', '1624', '530', ...",['this industry has affected the cultural attr...,"['T8', 'T7', 'T6', 'T10', 'T9', 'T11']","['T4', 'T4', 'T4', 'T11', 'T5', 'T5']","['supports', 'supports', 'supports', 'supports...","['Against', 'For', 'For']",International tourism is now more common than ...,The last 50 years have seen a significant incr...,['This was due to the lack of adequate control...,['international tourism can create negative im...,"[(8, 4, 'supports'), (7, 4, 'supports'), (6, 4...","[(3, 1, 'Against'), (3, 2, 'Against'), (4, 1, ...",TEST,[the tourism bring large profit for the destin...
4,essay005.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Claim',...","['286', '1535', '388', '775', '1330', '566', '...","['359', '1652', '564', '883', '1425', '765', '...",['one who studies overseas will gain many skil...,"['T6', 'T7', 'T8', 'T9', 'T10', 'T11']","['T3', 'T4', 'T7', 'T4', 'T5', 'T5']","['supports', 'attacks', 'attacks', 'supports',...","['For', 'For', 'For', 'Against']",Living and studying overseas,It is every student's desire to study at a goo...,['Compared to the peers studying in the home c...,['studying at an overseas university gives ind...,"[(6, 3, 'supports'), (7, 4, 'attacks'), (8, 7,...","[(3, 1, 'For'), (3, 2, 'For'), (4, 1, 'For'), ...",TEST,[one who studies overseas will gain many skill...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,essay398.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['Claim', 'MajorClaim', 'Premise', 'Premise', ...","['254', '1751', '409', '557', '647', '778', '9...","['318', '1951', '541', '645', '767', '897', '1...",['many different characters exist between male...,"['T3', 'T4', 'T5', 'T6', 'T7', 'T13', 'T14', '...","['T8', 'T8', 'T8', 'T8', 'T8', 'T12', 'T12', '...","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'For', 'For']",We can not forcedly put the same numbers of ma...,There is a view that universities and colleges...,['Most of male students tend to use their left...,['boys and girls have the diversity in psychol...,"[(3, 8, 'supports'), (4, 8, 'supports'), (5, 8...","[(1, 2, 'For'), (8, 2, 'For'), (10, 2, 'For'),...",TEST,[many different characters exist between male ...
398,essay399.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['367', '1323', '527', '431', '661', '787', '9...","['429', '1390', '645', '525', '737', '951', '1...",['this is a worrying tread which has negative ...,"['T4', 'T5', 'T6', 'T8', 'T10']","['T3', 'T3', 'T7', 'T7', 'T9']","['supports', 'supports', 'supports', 'supports...","['For', 'For', 'For']","Drugs, alcohol and messy sex lives","Celebrities, for example movie stars, are usua...",['The first impression of the celebrities seem...,['This gives children the idea that it is not ...,"[(4, 3, 'supports'), (5, 3, 'supports'), (6, 7...","[(3, 1, 'For'), (3, 2, 'For'), (7, 1, 'For'), ...",TRAIN,[this is a worrying tread which has negative i...
399,essay400.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Claim', 'Premise...","['274', '1619', '736', '541', '805', '389', '1...","['387', '1812', '796', '723', '944', '524', '1...",['governments should devote a greater portion ...,"['T4', 'T5', 'T6', 'T7', 'T9', 'T8']","['T3', 'T3', 'T3', 'T8', 'T8', 'T10']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",A greater proportion of the budget should be a...,"In today's world, the concept of the welfare s...",['decreasing the number of patients in the hea...,['society should be educated and became aware ...,"[(4, 3, 'supports'), (5, 3, 'supports'), (6, 3...","[(3, 1, 'For'), (3, 2, 'For'), (10, 1, 'For'),...",TRAIN,[governments should devote a greater portion o...
400,essay401.ann,"['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8...","['MajorClaim', 'MajorClaim', 'Premise', 'Premi...","['311', '1496', '502', '622', '386', '954', '1...","['384', '1667', '607', '815', '488', '1087', '...",['fatherhood is a as vital part of a healty pa...,"['T3', 'T7', 'T10', 'T4', 'T9', 'T6']","['T5', 'T6', 'T8', 'T3', 'T8', 'T8']","['supports', 'supports', 'supports', 'supports...","['For', 'For']",Fatherhood should be as present as motherhood ...,"In today's world, having and raising children ...","[""the role models within a family play a signi...","[""The first reason why the father's role shoul...","[(3, 5, 'supports'), (7, 6, 'supports'), (10, ...","[(5, 1, 'For'), (5, 2, 'For'), (8, 1, 'For'), ...",TRAIN,[fatherhood is a as vital part of a healty par...
401,essay402.ann,"['T1', 'T2', 'T3', 'T5', 'T6', 'T7', 'T8', 'T4...","['MajorClaim', 'MajorClaim', 'Premise', 'Premi...","['238', '1543', '379', '544', '725', '827', '3...","['307', '1620', '462', '723', '810', '896', '3...",['both of studying hard and playing sports are...,"['T5', 'T3', 'T6', 'T11', 'T12', 'T4', 'T13', ...","['T8', 'T8', 'T5', 'T10', 'T13', 'T15', 'T4', ...","['supports', 'supports', 'supports', 'supports...","['For', 'For']",Children should studying hard or playing sport...,Some people believe that studying hard is esse...,['children who always studying hard and gettin...,['studying hard will give children a better fu...,"[(4, 7, 'supports'), (3, 7, 'supports'), (5, 4...","[(7, 1, 'For'), (7, 2, 'For'), (15, 1, 'For'),...",TRAIN,[both of studying hard and playing sports are ...

In [203]:
essays_df['sorted_acs'] = df.sorted_acs.tolist()

In [204]:
essays_df

,para_id,AR_types,ac_count,AR_pairs,AC_types,all_para_pairs,p_id,correct_para_pairs,corrected_true_pairs,sorted_acs
0,"[0, 1, 2, 3, 4]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 5, 1]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0), (4...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(2, 3), (2, 4), (2, 5)], [(7, 6), (1...",[we should attach more importance to cooperati...
1,"[5, 6, 7, 8, 9]","[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 6, 2]","[[], [], [(4, 0), (4, 1), (4, 2), (4, 3)], [(5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (6, 3), (6, 4), (6, 5)], [(1...",[they are able to sustain their cultural ident...
2,"[10, 11, 12, 13, 14]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9...",[it has contributed to the economic developmen...
3,"[15, 16, 17, 18, 19, 20]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 3, 0]","[[], [], [(3, 0), (3, 1), (3, 2)], [(3, 0), (3...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(9, 6), (9...",[the tourism bring large profit for the destin...
4,"[21, 22, 23, 24, 25]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 6, 2]","[[], [], [(3, 0), (3, 1), (3, 2)], [(5, 0), (5...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(5, 2), (5, 3), (5, 4)], [(11, 6), (...",[one who studies overseas will gain many skill...
...,...,...,...,...,...,...,...,...,...,...
397,"[2208, 2209, 2210, 2211, 2212]","[[], [], ['Support', 'Support'], ['Support', '...","[0, 1, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], []]","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], []]",[many different characters exist between male ...
398,"[2213, 2214, 2215, 2216, 2217, 2218]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 0, 4, 2, 2, 3]","[[], [], [(0, 1), (0, 2), (0, 3)], [(1, 0)], [...","[[], [], ['Claim', 'Premise', 'Premise', 'Prem...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4, 5]","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[[], [], [(1, 2), (1, 3), (1, 4)], [(6, 5)], [...",[this is a worrying tread which has negative i...
399,"[2219, 2220, 2221, 2222, 2223]","[[], [], ['Support', 'Support', 'Support', 'Su...","[0, 1, 5, 3, 2]","[[], [], [(4, 0), (2, 1), (4, 2), (4, 3)], [(1...","[[], ['MajorClaim'], ['Premise', 'Premise', 'P...","[[], [], [(1, 2), (1, 3), (1, 4), (1, 5), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (2, 6), (3, ...","[[], [], [(6, 2), (4, 3), (6, 4), (6, 5)], [(8...",[governments should devote a greater portion o...
400,"[2224, 2225, 2226, 2227, 2228, 2229]","[[], [], ['Support', 'Attack'], ['Support', 'S...","[0, 1, 3, 3, 3, 2]","[[], [], [(0, 1), (0, 2)], [(0, 1), (0, 2)], [...","[[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...","[[], [], [(1, 2), (1, 3), (2, 1), (2, 3), (3, ...","[0, 1, 2, 3, 4, 5]","[[], [], [(2, 3), (2, 4), (3, 2), (3, 4), (4, ...","[[], [], [(2, 3), (2, 4)], [(5, 6), (5, 7)], [...",[fatherhood is a as vital part of a healty par...
401,"[2230, 2231, 2232, 2233, 2234]","[[], [], ['Support', 'Support', 'Support'], ['...","[0, 1, 4, 4, 1]","[[], [], [(2, 0), (2, 1), (2, 3)], [(2, 1), (0...","[[], ['MajorClaim'], ['Premise', 'Premise', 'C...","[[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...","[0, 1, 2, 3, 4]","[[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...","[[], [], [(4, 2), (4, 3), (4, 5)], [(8, 7), (6...",[both of studying hard and playing sports are ...

In [234]:
def get_whatever(row):
    
    result = []
    start = 0  # Start index for slicing

    for count in row.ac_count:
        result.append(row.sorted_acs[start:start + count])
        start += count  # Move the start index forward
    
    # acs_by_para = []
    
    # start = 0
    
    # for c in row.ac_count:
        
    #     tmp = [""] * (c + 1)
        
    #     for i in range(start, start + c):
    #         tmp[i] = row.sorted_acs[i]
        
    #     start = start + c
        
    #     acs_by_para.append(tmp)
    #     ##end_idx = start_idx + len(ac_count[p])
        
    return result

In [235]:
# def unflatten(l, ll):
#     iterator = iter(l)  # Iterator for l
#     result = []  # To store the final nested list
#     stack = [(result, ll)]  # Stack to track positions

#     while stack:
#         current_list, template = stack.pop()  # Get the current position in the result list

#         for item in template:
#             if isinstance(item, list):
#                 new_sublist = []  # Create a new sublist
#                 current_list.append(new_sublist)  # Append it to the current result list
#                 stack.append((new_sublist, item))  # Push it to the stack for later processing
#             else:
#                 current_list.append(next(iterator))  # Replace with next element from l

#     return result

In [236]:
essays_df['acs_by_para'] = essays_df.apply(lambda row: get_whatever(row), axis=1)

In [248]:
essays_df.iloc[70]['AC_types']

['[]',
 "['MajorClaim']",
 "['Claim', 'Premise', 'Premise', 'Premise']",
 "['Premise', 'Claim']",
 "['Premise', 'Premise', 'Claim']",
 "['MajorClaim', 'Claim']"]

In [247]:
essays_df.iloc[70]['acs_by_para']

[[],
 ['while some of them are disturbing, we can not overlook other merits the advertisements bring'],
 ['it is unfair to restrict those public service advertisements which are creative and inspiring',
  'they are not in the purpose of making profits but taking a role of disseminating valued culture, good moral traits and calling for helps for the disabled and the poor',
  'publicizing brand image or a particular product of mass media could boost sales for companies',
  'it could simulate household spending and therefore promote the economic development of the whole country'],
 ['A recent study shows that after launching an advertising campaign, the sales revenue would increase by 40%, which is the very fact to verify its positive influences on economic',
  'the advertising expenses lead to a higher product price and some of them express fake information, creating information asymmetry between consumers and companies'],
 ['its merits still outweigh these downsides',
  'advertisements have its social responsibility and contribute to economic growth'],
 []]

In [246]:
essays_df.iloc[70]['sorted_acs']

['while some of them are disturbing, we can not overlook other merits the advertisements bring',
 'it is unfair to restrict those public service advertisements which are creative and inspiring',
 'they are not in the purpose of making profits but taking a role of disseminating valued culture, good moral traits and calling for helps for the disabled and the poor',
 'publicizing brand image or a particular product of mass media could boost sales for companies',
 'it could simulate household spending and therefore promote the economic development of the whole country',
 'A recent study shows that after launching an advertising campaign, the sales revenue would increase by 40%, which is the very fact to verify its positive influences on economic',
 'the advertising expenses lead to a higher product price and some of them express fake information, creating information asymmetry between consumers and companies',
 'its merits still outweigh these downsides',
 'advertisements have its social responsibility and contribute to economic growth']

In [244]:
essays_df.iloc[70]

para_id                                    [389, 390, 391, 392, 393, 394]
AR_types                [[], [], ['Support', 'Support', 'Support'], ['...
ac_count                                               [0, 1, 4, 2, 3, 2]
AR_pairs                [[], [], [(0, 1), (3, 2), (0, 3)], [(1, 0)], [...
AC_types                [[], ['MajorClaim'], ['Claim', 'Premise', 'Pre...
all_para_pairs          [[], [], [(1, 2), (1, 3), (1, 4), (2, 1), (2, ...
p_id                                                   [0, 1, 2, 3, 4, 5]
correct_para_pairs      [[], [], [(2, 3), (2, 4), (2, 5), (3, 2), (3, ...
corrected_true_pairs    [[], [], [(2, 3), (5, 4), (2, 5)], [(7, 6)], [...
sorted_acs              [while some of them are disturbing, we can not...
acs_by_para             [[], [while some of them are disturbing, we ca...
triplets                [[], [], [((2, 3), Support), ((2, 4), NR), ((2...
Name: 70, dtype: object

In [245]:
for para, types in zip(essays_df.iloc[70].acs_by_para, essays_df.iloc[70].AC_types):
    
    print(para, types)

[] []
['while some of them are disturbing, we can not overlook other merits the advertisements bring'] ['MajorClaim']
['it is unfair to restrict those public service advertisements which are creative and inspiring', 'they are not in the purpose of making profits but taking a role of disseminating valued culture, good moral traits and calling for helps for the disabled and the poor', 'publicizing brand image or a particular product of mass media could boost sales for companies', 'it could simulate household spending and therefore promote the economic development of the whole country'] ['Claim', 'Premise', 'Premise', 'Premise']
['A recent study shows that after launching an advertising campaign, the sales revenue would increase by 40%, which is the very fact to verify its positive influences on economic', 'the advertising expenses lead to a higher product price and some of them express fake information, creating information asymmetry between consumers and companies'] ['Premise', 'Claim']
['its merits still outweigh these downsides', 'advertisements have its social responsibility and contribute to economic growth'] ['Premise', 'Premise', 'Claim']
[] ['MajorClaim', 'Claim']

In [241]:
essays_df.iloc[0]['AC_types']

['[]',
 "['MajorClaim']",
 "['Claim', 'Premise', 'Premise', 'Premise']",
 "['Premise', 'Claim', 'Premise', 'Premise', 'Claim']",
 "['MajorClaim']"]